### ISSUE TITLE
Union as type argument does not work for remote types

### ISSUE THREAD

**Issue by dvic** [Qqwy/elixir-type_check#164]
Example:

```elixir
defmodule Foo do
  use TypeCheck

  defstruct [:name]
  @type! t(name) :: %__MODULE__{name: name}

  # compiles
  @type! instance1 :: t(:foo)
  # compiles
  @type! instance2 :: t(:foo | :bar)
end

defmodule Instances do
  use TypeCheck

  # compiles
  @type! instance1 :: Foo.t(:foo)
  # does not compile
  @type! instance2 :: Foo.t(:foo | :bar)
  # == Compilation error in file lib/foo.ex ==
  #   ** (CompileError) lib/foo.ex:19: undefined function |/2 (expected TypeCheck.Internals.UserTypes.Instances to define such a function or for it to be imported, but none are available)
  #       (type_check 0.12.4) expanding macro: TypeCheck.Macros.__before_compile__/1
  #       lib/foo.ex:13: Instances (module)
end
```

And the `instance1` example also does not seem to compile when reference remotely in a `spec!`:

```elixir
defmodule Foo do
  use TypeCheck

  defstruct [:name]
  @type! t(name) :: %__MODULE__{name: name}

  # compiles
  @type! instance1 :: t(:foo)

  # compiles
  @spec! some_fun :: instance1()
  def some_fun do
  end
end

defmodule Instances do
  use TypeCheck

  # compiles
  @type! instance1 :: Foo.t(:foo)

  # does not compile
  @spec! some_fun :: instance1()
  def some_fun do
  end

  # == Compilation error in file lib/foo.ex ==
  #   ** (TypeCheck.CompileError) Invalid value passed to a function expecting a type!
  #   `:foo` is not a valid TypeCheck type.
  #   You probably tried to use a TypeCheck type as a function directly.

  #   Instead, either implement named types using the `type`, `typep`, `opaque` macros,
  #   or use TypeCheck.Type.build/1 to construct a one-off type.

  #   Both of these will perform the necessary conversions to turn 'normal' datatypes to types.

  #   (If you _really_ want to build a type manually,
  #   be sure to use `TypeCheck.Builtin.literal/1`
  #   to turn a literal value into a type.)

  #       (type_check 0.12.4) lib/type_check/type.ex:108: TypeCheck.Type.ensure_type!/1
  #       lib/foo.ex:5: Foo.t/1
  #       lib/foo.ex:20: TypeCheck.Internals.UserTypes.Instances.instance1/0
  #       /Users/dvic/Development/demo/lib/foo.ex:23: (file)
  #       (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
  #       (elixir 1.14.1) lib/code.ex:825: Code.eval_quoted/3
end
```

**Comment by dvic** [comment]
I think the former bug is because `PreExpander.rewrite` is not called on the params, only on the type in `macros.ex`?

https://github.com/Qqwy/elixir-type_check/blob/f1848dfadaaf7f24ec982cc70f5701fd72c5314d/lib/type_check/macros.ex#L508-L515
